var request = require("request-promise");
var places = [
  "INDORE-MALWA MILL",
  "GWALIOR-OPPO. FILMISTAN",
  "LUCKNOW-ARJUNGANJ",
  "UNNAO-SHAHGANJ BAZAAR",
  "LUCKNOW-DUBAGGA",
  "JAIPUR-RAJAPARK",
  "AGRA",
  "RAJPURA-AGRA",
  "AGRA-SIKANDRA",
  "GIRIDIH",
  "HIRAPUR",
  "JAMTARA",
  "DHANBAD-BANK MORE",
  "DHANBAD-SARAIDHELLA",
  "RANCHI",
  "BIRSA CHOWK-RANCHI",
  "ADITYAPUR",
  "JAMSHEDPUR-SAKCHI AMBAGAN",
  "LAJPATNAGAR",
  "LAXMINAGAR",
  "CHOWK",
  "HUSSAINGANJ",
  "THAKURGANJ",
  "LUCKNOW-KHURRAM NAGAR",
  "LUCKNOW",
  "VIKAS NAGAR",
  "CANT ROAD",
  "BARABANKI",
  "AKBARPUR",
  "MAU",
  "MANGLAM",
  "RAJENDER NAGAR",
  "PADARI BAZAR",
  "SULTANPUR",
  "PARTAP GARH",
  "RAIBARELI",
  "DEORIA",
  "PADRAUNA",
  "BASTI",
  "FAIZABAD",
  "KHALILABAD",
  "FIROZABAD",
  "ETAWAH",
  "MAINPURI-STATION ROAD",
  "AZAMGARH",
  "BHAGESHWAR NAGAR",
  "JAUNPUR",
  "HUSAINABAD-JAUNPUR",
  "SARAI MIR",
  "GAZIPUR",
  "BALIA",
  "LALGANJ",
  "MOTIHARI",
  "BETTIAH",
  "CHAKIA",
  "DARBHANGA",
  "GOPALGANJ",
  "MADHUBANI",
  "KISHANGANJ",
  "PURNIA",
  "RAMBAGH CHOWK",
  "RAIGANJ-MG ROAD",
  "COOCH BEHAR",
  "JALPAIGURI",
  "SILIGURI",
  "DHUBRI-GTB ROAD",
  "CHHAPRA",
  "SIWAN",
  "HAJIPUR",
  "BEGUSARAI",
  "SAMASTIPUR",
  "KHAGARIA",
  "MUZAFFARNAGAR",
  "SAHARANPUR",
  "SAHARANPUR-DELHI ROAD",
  "HARIDWAR",
  "MANGLAUR",
  "FATHEPUR",
  "BANDA",
  "ALIGARH",
  "BADAUN",
  "HATHRAS",
  "MURADABAD",
  "SHAHAJAHANPUR",
  "BAREILLY",
  "PREM NAGAR-BAREILLY",
  "SITAPUR",
  "LAKHIMPUR",
  "SIDHAULI",
  "GONDA",
  "BAHRAICH",
  "KANPUR",
  "SAKET NAGAR",
  "LAL BANGLA-KANPUR",
  "MUNGER",
  "JAMALPUR",
  "LAKHISARAI",
  "SHEIKHPURA",
  "HALDWANI",
  "KASHIPUR",
  "RUDRAPUR",
  "CHANDIGARH",
  "AMBALA",
  "ZIRAKPUR-BUS STAND",
  "JALANDHAR",
  "PATHANKOT",
  "GURDASPUR",
  "SRINAGAR",
  "UDHAMPUR",
  "KATHUA",
  "VARANASI",
  "PAHARIA",
  "MUGHALSARAI",
  "AJMER",
  "NAGOUR",
  "UDAIPUR",
  "SANGANER-JAIPUR",
  "JAIPUR-JHOTWARA",
  "LAWGARDEN",
  "VADODARA",
  "MEHSANA",
  "JAMNAGAR",
  "GANDHIDHAM",
  "MORVI",
  "SHIVPURI",
  "SAGAR",
  "JABALPUR-DAMOHNAKA",
  "SITAMARHI",
  "MUZAFFARPUR",
  "SHEOHAR",
  "MUZAFFARPUR-MARIPUR CHOWK",
  "KEONJHAR",
  "BARIPADA",
  "DHENKANAL",
  "CUTTACK",
  "BERHAMPUR",
  "BHADRAK",
  "URBAN BANK ROAD",
  "BHUBANESWAR",
  "JHARSUGUDA",
  "SAMBALPUR",
  "NABARANGPUR",
  "GUMLA",
  "PATNA CITY",
  "KANKARBAGH-PATNA",
  "PATNA-KURJI",
  "ALLAHABAD",
  "KOTWALI",
  "REWA",
  "PILIBHIT",
  "AMROHA",
  "RAMPUR",
  "BISALPUR-EIDGAH CHAURAHA",
  "UDALGURI-MG ROAD",
  "MEERUT",
  "BIJNOR",
  "GARH ROAD-MEERUT",
  "JHANSI",
  "ORAI",
  "HAMIRPUR",
  "ARRAH",
  "BUXAR",
  "BHABUA",
  "SAHARSA",
  "MADHEPURA",
  "SUPAUL",
  "LUXA",
  "DURGAKUND",
  "BHOJUBEER",
  "BHOPAL",
  "UJJAIN",
  "BERASIA",
  "GWALIOR-SURYA NAGAR",
  "GWALIOR-LASHKAR",
  "INDORE-ANNAPURNA ROAD",
  "LATEHAR",
  "LOHARDAGA",
  "DALTONGANJ-REDMA CHOWK",
  "CHAAS",
  "PHUSRO",
  "RAMGARH",
  "AURANGABAD",
  "SASARAM",
  "DAUD NAGAR",
  "JEHANABAD-STATION ROAD",
  "BURDWAN",
  "PURULIA",
  "ARAMBAGH",
  "BHAGALPUR",
  "BANKA",
  "GODDA-BHAGALPUR ROAD",
  "KAHALGOAN",
  "KHARAGPUR",
  "BANDEL",
  "CONTAI",
  "TAMLUK-MANIKTALA",
  "KOLKATA-BARASAT",
  "GORAKHPUR",
  "MAHARAJGANJ",
  "GORAKHPUR-RUSTAMPUR",
  "GORAKHPUR-MEDICAL COLLEGE",
  "RAJAJIPURAM",
  "TELIBAGH",
  "GAURIGANJ",
  "SHUKLAGANJ",
  "KANGRA-BUS STAND",
  "SOLAN-ANAND COMPLEX",
  "PALAMPUR-CITY MALL",
  "JAMMU",
  "KACHI CHAWNI",
  "JAMMU-KUNJWANI",
  "JAMMU-TALAB TILLO",
  "PALKI-LUCKNOW",
  "CHINHAT-LUCKNOW",
  "AIRPORT ROAD-LUCKNOW",
  "LUCKNOW-BUDHESHWAR",
  "FARRUKHABAD",
  "KANNAUJ",
  "NAUBASTA-KANPUR",
  "DEHRADUN",
  "DALANWALA-DEHRADUN",
  "MAJRA-DEHRADUN",
  "CHURCH ROAD",
  "NAWADA",
  "JAMUI",
  "MATHURA",
  "SHAHGANJ",
  "KRISHNANAGAR-WEST BENGAL",
  "SHANTIPUR",
  "MURSHIDABAD",
  "BHANGEL",
  "BULANDSHAHR-RAJA BABU RD",
  "GHAZIABAD",
  "JHANGIRABAD-BHOPAL",
  "BHOPAL-KAROND",
  "BHOPAL-CHUNABHATTI",
  "NALBARI",
  "ITANAGAR",
  "BISWANATH CHARIALI",
  "KHARUPETIA-PANBARI ROAD",
  "ZOO ROAD-GUWAHATI",
  "KALAPAHAR-GUWAHATI",
  "JOWAI",
  "BARPETA ROAD",
  "HARDOI-LUCKNOW ROAD",
  "LUCKNOW-ASHIYANA",
  "LUCKNOW-BKT",
  "NAGAON",
  "JORHAT",
  "DIBRUGARH-JHALUKPARA",
  "KOTA",
  "KOTA-RANGBARI",
  "KOTA-KUNADI",
  "RAJIV NAGAR",
  "BORING ROAD-PATNA",
  "SAGUNA MOR-PATNA",
  "RENUKOOT",
  "GARHWA",
  "MIRZAPUR",
  "DELHI-NARELA",
  "KANPUR-KALYANPUR",
  "JAMMU-JANIPUR",
  "KOHIMA-NORTH BLOCK",
  "LUCKNOW-QAISARBAGH",
  "LUCKNOW-RAJAJIPURAM 2",
  "DUMKA",
  "DEOGHAR",
  "DHULIYAN",
  "FACTORY OUTLET_BILASPUR",
  "CORPORATE SALE_TAORU",
  "RAJOURI",
  "AKHNOOR-LOHRI MALL"
];
// places.forEach((item,index)=>{
//     getGooglePlace(item,index)
// })
getGooglePlace('getGooglePlace',2)
function getGooglePlace(name,index){
    request(
        `https://maps.googleapis.com/maps/api/place/textsearch/json?query=${
          name
        }&key=AIzaSyAAr72wA5Am-wFBUwYlwL9JFBhCNl9QXx8`,
        { json: true }
      )
        .then(res => {
          let place = {
            hubId: null,
            boundary: null,
            address: res["results"][0].formatted_address,
            accessibility: "public",
            addedBy: "fc5e734a-2878-45e5-872a-14338d5578c6",
            center: {
              latitude: res["results"][0].geometry.location.lat,
              longitude: res["results"][0].geometry.location.lng
            },
            suggestedRadius: 250,
            isOwned: false,
            centerCoordinates: [
              res["results"][0].geometry.location.lng,
              res["results"][0].geometry.location.lat
            ],
            placeId: null,
            externalId: null,
            geoJsonBoundry: null,
            source: "FRETRON",
            places: null,
            viewport: null,
            district: null,
            name: name,
            state: null,
            category: "Fleet Office",
            subDistrict: null
          };
          console.log({index:index,place:place});
          cp(place)
        })
        .catch(err => console.log(err));
      
}

function cp(place) {
  var options = {
    method: "POST",
    uri: "http://apis.fretron.com/place-manager/v2/place",
    body: place,
    json: true,
    headers: {
      "Content-Type": "application/json",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzkwODIyNTEsInVzZXJJZCI6IjAwZTEzODAyLTI3ZjEtNGM4OC04ZmIyLWRkN2VjMmM3NmZkNSIsImVtYWlsIjoiYWthc2guZHV0dGFAZnJldHJvbi5jb20iLCJtb2JpbGVOdW1iZXIiOiI5Nzc2MjE3NzY5Iiwib3JnSWQiOiJmYzVlNzM0YS0yODc4LTQ1ZTUtODcyYS0xNDMzOGQ1NTc4YzYiLCJuYW1lIjoiQUtBU0ggRFVUVEEiLCJvcmdUeXBlIjoiRkxFRVRfT1dORVIiLCJpc0dvZCI6dHJ1ZSwicG9ydGFsVHlwZSI6ImJhc2ljIn0.aOYyNCmyoXbjnlpfVFKINaig-Vl-gQj8FMkz7TkXwqM"
    }
  };
  request(options)
    .then(res => {
      console.log(res);
    })
    .catch(err => console.log(err));
}

