var suggetion = {
  load: {
    freightUnit: {
      lineItems: [
        {
          salesOrderMappings: [
            {
              quantity: {
                volume: null,
                packageMeasurement: null,
                weight: null,
                trucks: 1,
              },
              orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
              lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
              legType: "DirectLeg",
              consignmentId: null,
              consignmentLineItemId: null,
              uuid: "1ebaa8ed-8963-40b1-b886-0b06bb89ec52",
              fuMappings: [
                {
                  executionPlanId: null,
                  legType: "DirectLeg",
                  fuLineItemId: null,
                  legId: null,
                  legStatus: null,
                },
              ],
            },
          ],
          optimisationBasis: "trucks",
          expectedFreightINR: 1200,
          stageStartTime: 1610629454217,
          purchaseLineItemId: "880361d0-f6ac-4e9f-8061-77c36a4bcde5",
          loadTypeId: "a8acf219-1fb8-4974-a2f1-929de6af8231",
          finalizationIssues: null,
          expectedStageEndTime: 1610617052327,
          utilization: 100,
          uuid: "0a3ea62d-74a3-4eaf-8bbe-0c70533d1217",
          issues: null,
          freightType: "perMT",
          auctionId: null,
          alerts: null,
          transporterId: "de98295e-3299-4ce8-a34e-de8d138b3499",
          purchaseOrderId: "043a9f92-82be-45c7-a231-ce6b77aa2b40",
          shipmentId: null,
          status: "ALLOCATED",
        },
      ],
      documentDate: 1610616963636,
      totalQuantity: {
        volume: null,
        packageMeasurement: null,
        weight: null,
        trucks: 1,
      },
      auctionQuantity: null,
      customFields: null,
      documentNumber: "FL0000932",
      allocatedQuantity: {
        volume: null,
        packageMeasurement: null,
        weight: null,
        trucks: 1,
      },
      allowedLoadTypes: [
        {
          bodyType: "FULL BODY",
          passingCapacityMT: 19,
          passingCapacityCFT: 670.8900000000001,
          bodyTypes: null,
          partnerName: null,
          minLength: 0,
          includeMinLength: true,
          partnerExternalId: null,
          chassisTypes: null,
          updates: null,
          uuid: "a8acf219-1fb8-4974-a2f1-929de6af8231",
          orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
          vehicleCategory: "TRUCK",
          includeMaxLength: true,
          numberOfWheels: null,
          minHeight: 7,
          chassisType: "TRUCK-10W",
          includeMinHeight: true,
          maxHeight: 8,
          name: "TRUCK-10W_FULLBODY_22FT",
          partnerId: null,
          includeMaxHeight: true,
          dimensionString: null,
          maxLength: 22,
        },
      ],
      updates: {
        traceID: "01ef89be-80b4-4c0c-afdd-8b98abbbf157",
        resourceId: "2f8a98a9-3f9c-4ce6-84d0-506c152ea357",
        updatedBy: "USER",
        sourceOfInformation: "USER",
        description: "Allocated 1 vehicles to transporter FLEET-SPL-NAGPUR.",
        forwardReasons: ["freight.unit.allocate.transporter.event"],
        userId: "06ddafd2-dafd-45d2-a94d-26375d6712e7",
        uuid: "b4f7b21e-124d-48a9-ab1f-b14b69f67f31",
        revision: 4,
        time: 1610629454426,
        forwardedFrom: "de98295e-3299-4ce8-a34e-de8d138b3499",
        resourceType: "FreightUnit",
        updateType: null,
      },
      type: "Planned",
      uuid: "2f8a98a9-3f9c-4ce6-84d0-506c152ea357",
      orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
    },
    orders: [
      {
        orderType: null,
        orderNumber: "SO952381",
        attachments: null,
        customFields: null,
        contractUuid: null,
        updates: null,
        uuid: "28282ca4-32f6-4324-b67e-3ea97db46213",
        payer: null,
        issues: null,
        orgId: null,
        lineItems: [
          {
            allowedCustomerLoadTypes: [
              {
                bodyType: null,
                passingCapacityMT: null,
                passingCapacityCFT: null,
                bodyTypes: ["FULL BODY"],
                partnerName: "PIDILITE INDUSTRIES LIMITED",
                minLength: null,
                includeMinLength: false,
                partnerExternalId: "0010108505",
                chassisTypes: ["TRUCK-10W"],
                updates: {
                  traceID: null,
                  resourceId: "f3aeed32-0faa-4714-aa3b-cd267fc4fc4e",
                  updatedBy: "USER",
                  sourceOfInformation: null,
                  description: "Updated Customer Load Type .",
                  forwardReasons: ["customer.load.type.updated.event"],
                  userId: "b3104efc-c77b-4095-99b1-bdd9327b94e4",
                  uuid: "5e590f24-5b78-46d6-a5d2-548f05b92bcf",
                  revision: null,
                  time: 1606803723983,
                  forwardedFrom: null,
                  resourceType: "CustomerLoadTypes",
                  updateType: null,
                },
                uuid: "f3aeed32-0faa-4714-aa3b-cd267fc4fc4e",
                orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
                vehicleCategory: "TRUCK",
                includeMaxLength: false,
                numberOfWheels: null,
                minHeight: null,
                chassisType: null,
                includeMinHeight: false,
                maxHeight: null,
                name: "TAURUS 15 MT",
                partnerId: "92015121-47ef-4f2a-bf06-4d8bd5baf965",
                includeMaxHeight: false,
                dimensionString: null,
                maxLength: null,
              },
            ],
            freightUnitLineItemIds: [
              "f3f9806c-b8a7-4884-be36-b56bdb2dc87d",
              "5705f925-0670-4808-929b-33013b44d3ed",
              "a783c576-e33f-4dac-97a3-797195437dc1",
              "e4d635d9-c97d-443a-a0f8-079f87ffc64b",
              "0a3ea62d-74a3-4eaf-8bbe-0c70533d1217",
            ],
            remainingPlannedQuantity: {
              volume: null,
              packageMeasurement: null,
              weight: null,
              trucks: 0,
            },
            customFields: null,
            expectedPickupDate: 1610735399468,
            loadInfo: {
              material: "CHEMICAL",
              valueOfGoods: null,
              standardMeasurement: {
                volume: null,
                packageMeasurement: null,
                weight: null,
                trucks: 5,
              },
              currency: null,
              measurements: [],
            },
            auctionIds: null,
            allowedLoadTypes: [],
            invoiceValue: null,
            uuid: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
            consigner: {
              geoFence: null,
              address: null,
              documents: null,
              verificationStatus: "Verified",
              customFields: null,
              isPortalEnabled: false,
              externalId: "0010109303",
              panNumber: null,
              type: "customer",
              updates: null,
              aadharNo: null,
              uuid: "848c0835-1524-497f-872d-6dc6bd13d4e1",
              orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
              parentId: null,
              places: [
                {
                  hubId: null,
                  boundary: null,
                  address: "KALA AMB ,INDIA",
                  accessibility: "private",
                  addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
                  center: {
                    latitude: 30.4992,
                    longitude: 77.207,
                  },
                  suggestedRadius: 100000,
                  isOwned: null,
                  centerCoordinates: [77.207, 30.4992],
                  placeId: "c905e833-8e42-46bc-832d-e305347d89b7",
                  geoJsonBoundry: null,
                  externalId: "08KL M",
                  source: "hubs",
                  places: [],
                  viewport: {
                    southwest: {
                      latitude: 29.90241428,
                      longitude: 76.46970085199999,
                    },
                    northeast: {
                      latitude: 31.095985719999998,
                      longitude: 77.944299148,
                    },
                  },
                  district: null,
                  name: "KALA AMB",
                  state: null,
                  category: "Hub",
                  subDistrict: null,
                },
              ],
              route: null,
              gstn: null,
              name: "PIDILITE IND LTD",
              voterId: null,
              location: null,
              fretronId: null,
              contacts: [
                {
                  emails: [],
                  address: null,
                  mobileNumbers: [],
                  mobileNumber: null,
                  name: "PIDILITE IND LTD",
                  type: null,
                },
              ],
              status: "ACTIVE",
              group: {
                name: "Consignor",
                partnerType: null,
                uuid: null,
                orgId: null,
              },
            },
            freightChargeRate: 234950,
            allowedTransitDays: 4,
            invoiceNumber: null,
            customerMaterial: null,
            consignmentBranch: null,
            consignee: {
              geoFence: null,
              address: null,
              documents: null,
              verificationStatus: null,
              customFields: null,
              isPortalEnabled: false,
              externalId: "13PNVL",
              panNumber: null,
              type: null,
              updates: null,
              aadharNo: null,
              uuid: null,
              orgId: null,
              parentId: null,
              places: [
                {
                  hubId: null,
                  boundary: null,
                  address: "PANVEL ,INDIA",
                  accessibility: "private",
                  addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
                  center: {
                    latitude: 18.9894,
                    longitude: 73.1175,
                  },
                  suggestedRadius: 100000,
                  isOwned: null,
                  centerCoordinates: [73.1175, 18.9894],
                  placeId: "25b2c291-ddde-40c7-bba7-fe2875bfed6c",
                  geoJsonBoundry: null,
                  externalId: "13PNVL",
                  source: "hubs",
                  places: [],
                  viewport: {
                    southwest: {
                      latitude: 18.39261428,
                      longitude: 72.380200852,
                    },
                    northeast: {
                      latitude: 19.58618572,
                      longitude: 73.85479914800001,
                    },
                  },
                  district: null,
                  name: "PANVEL",
                  state: null,
                  category: "Hub",
                  subDistrict: null,
                },
              ],
              route: null,
              gstn: null,
              name: "PANVEL",
              voterId: null,
              location: null,
              fretronId: null,
              contacts: null,
              status: null,
              group: null,
            },
            legType: "DirectLeg",
            plannedQuantity: null,
            externalId: "000100",
            invoiceDate: null,
            fuMappings: [],
            mappings: [
              {
                quantity: {
                  volume: null,
                  packageMeasurement: null,
                  weight: null,
                  trucks: 1,
                },
                orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
                lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
                legType: null,
                consignmentId: null,
                consignmentLineItemId: null,
                uuid: "1d087128-e671-4ec9-86db-28416e9ab978",
                fuMappings: [
                  {
                    executionPlanId: null,
                    legType: "DirectLeg",
                    fuLineItemId: "f3f9806c-b8a7-4884-be36-b56bdb2dc87d",
                    legId: null,
                    legStatus: "AUCTIONED",
                  },
                ],
              },
              {
                quantity: {
                  volume: null,
                  packageMeasurement: null,
                  weight: null,
                  trucks: 1,
                },
                orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
                lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
                legType: null,
                consignmentId: null,
                consignmentLineItemId: null,
                uuid: "cdabf54b-dbb5-408b-91a9-32f905f9d257",
                fuMappings: [
                  {
                    executionPlanId: null,
                    legType: "DirectLeg",
                    fuLineItemId: "5705f925-0670-4808-929b-33013b44d3ed",
                    legId: null,
                    legStatus: "AUCTIONED",
                  },
                ],
              },
              {
                quantity: {
                  volume: null,
                  packageMeasurement: null,
                  weight: null,
                  trucks: 1,
                },
                orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
                lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
                legType: null,
                consignmentId: null,
                consignmentLineItemId: null,
                uuid: "c66d86c0-040c-4b4f-b5ac-d6836a4c8aad",
                fuMappings: [
                  {
                    executionPlanId: null,
                    legType: "DirectLeg",
                    fuLineItemId: "a783c576-e33f-4dac-97a3-797195437dc1",
                    legId: null,
                    legStatus: "AUCTIONED",
                  },
                ],
              },
              {
                quantity: {
                  volume: null,
                  packageMeasurement: null,
                  weight: null,
                  trucks: 1,
                },
                orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
                lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
                legType: null,
                consignmentId: null,
                consignmentLineItemId: null,
                uuid: "17165520-b553-4e4e-a0ce-ad7f76e0cdd5",
                fuMappings: [
                  {
                    executionPlanId: null,
                    legType: "DirectLeg",
                    fuLineItemId: "e4d635d9-c97d-443a-a0f8-079f87ffc64b",
                    legId: null,
                    legStatus: "PLANNED",
                  },
                ],
              },
              {
                quantity: {
                  volume: null,
                  packageMeasurement: null,
                  weight: null,
                  trucks: 1,
                },
                orderId: "28282ca4-32f6-4324-b67e-3ea97db46213",
                lineItemId: "70d4d5cd-0285-4123-a9be-d83f33bd9af3",
                legType: null,
                consignmentId: null,
                consignmentLineItemId: null,
                uuid: "1ebaa8ed-8963-40b1-b886-0b06bb89ec52",
                fuMappings: [
                  {
                    executionPlanId: null,
                    legType: "DirectLeg",
                    fuLineItemId: "0a3ea62d-74a3-4eaf-8bbe-0c70533d1217",
                    legId: null,
                    legStatus: "ALLOCATED",
                  },
                ],
              },
            ],
            material: {
              unitOfMeasurement: "Metric Tonnes",
              materialType: "DARCL  Lifted Material",
              externalId: "000000000050000118",
              updates: null,
              taxCode: null,
              uuid: "5d2af863-25a5-415d-a869-6df6d1d3a668",
              orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
              pricePerUnit: null,
              division: null,
              controlCode: null,
              materialGroup: "Darcl TPT Material",
              name: "CHEMICAL",
              measurementType: "weight",
            },
            service: {
              unitOfMeasurement: "trucks",
              materialType: "Service",
              externalId: "TPT_SER_GTA_TLD",
              updates: null,
              taxCode: null,
              uuid: "2a57e77b-c7a9-43c0-8a43-5686ca8ceffd",
              orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
              pricePerUnit: null,
              division: "Road Services",
              controlCode: "996511",
              materialGroup: "Services for Sale",
              name: "TRANSPORT SERVICE-GTA-VEHICLE (TLD) BASE",
              measurementType: "trucks",
            },
            freightChargeType: null,
            status: "PLANNED",
          },
        ],
        contractExternalId: null,
        terms: null,
        contractLineItemId: null,
        paymentCollectionBranch: null,
        expireDate: null,
        consignmentBranch: null,
        allowedExecutionProfiles: null,
        orderReceiveDate: null,
        salesOffice: null,
        toleranceQuantity: null,
        externalId: "3002197798",
        billToParty: null,
        alerts: null,
        statusDescription: null,
        route: null,
        secondaryStatus: null,
        billingBranch: null,
        contractBranch: null,
        orderDate: null,
        status: null,
        customer: null,
      },
    ],
  },
  vlr: {
    isActiveVLR: false,
    updatedBy: null,
    customFields: null,
    vehicleSupervisor: {
      address: null,
      profileThumbnailString: null,
      mobileNumber: null,
      authToken: null,
      updates: null,
      uuid: null,
      mergedUserIds: null,
      isGod: null,
      profileDocumentId: null,
      otpEnabled: null,
      onBoardingType: null,
      alternateEmails: null,
      name: "AMRIK.LAYAL@DARCL.COM",
      tokens: null,
      alternateMobileNumbers: null,
      email: null,
    },
    currentNearestHub: null,
    currentHubDetails: {
      hubId: null,
      boundary: null,
      address: "PATNA ,INDIA",
      accessibility: "private",
      addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
      center: {
        latitude: 25.5940947,
        longitude: 85.1375645,
      },
      suggestedRadius: 100000,
      isOwned: null,
      centerCoordinates: [85.1375645, 25.5940947],
      placeId: "53fc257c-1530-4bda-9c13-71c65b6b9a62",
      geoJsonBoundry: null,
      externalId: "04PANA",
      source: "hubs",
      places: [],
      viewport: {
        southwest: {
          latitude: 24.99730898,
          longitude: 84.40026535199999,
        },
        northeast: {
          latitude: 26.19088042,
          longitude: 85.874863648,
        },
      },
      district: null,
      name: "PATNA",
      state: null,
      category: "Hub",
      subDistrict: null,
    },
    currentHub: "PATNA",
    lastTripPointCompletionTime: 1603362801000,
    updates: {
      traceID: null,
      resourceId: null,
      updatedBy: null,
      sourceOfInformation: null,
      description: null,
      forwardReasons: null,
      userId: null,
      uuid: null,
      revision: null,
      time: 1610953203301,
      forwardedFrom: null,
      resourceType: null,
      updateType: null,
    },
    activeShipment: {
      creationTime: null,
      customFields: null,
      transportationMode: null,
      freightUnitLineItemId: null,
      lastSyncUpTime: null,
      updates: null,
      isActive: false,
      uuid: null,
      issues: null,
      branch: null,
      orgId: null,
      shipmentType: null,
      completionTime: null,
      routeId: null,
      shipmentTrackingStatus: null,
      lastForwardTime: null,
      links: null,
      shipmentDate: null,
      shipmentNumber: null,
      originalEdd: null,
      edd: 1603463768000,
      externalShipmentId: null,
      fleetInfo: {
        forwardingAgent: null,
        verificationStatus: null,
        trackingMode: null,
        broker: null,
        uuid: null,
        orgId: null,
        vehicle: null,
        driver: {
          pincode: null,
          dlExpiryTime: null,
          attachedDocs: [],
          address: null,
          mobileNumbers: null,
          dlNumber: null,
          mobileNumber: "9355977555",
          customFields: null,
          externalId: "00110474",
          updates: {
            traceID: null,
            resourceId: "0b30550c-6ce7-40b0-8704-4e3f07c5aeee",
            updatedBy: "USER",
            sourceOfInformation: null,
            description:
              "changed driving license expire date from 22/10/2020  to 22/10/2020 ",
            forwardReasons: [
              "driver.update.event",
              "driver.license.expiry.date.updated",
            ],
            userId: "afa3e041-29b4-475a-9e5b-2ee634426933",
            uuid: "0ab69b3f-d403-4765-ba4c-0fa6fe857965",
            revision: null,
            time: 1603356272687,
            forwardedFrom: null,
            resourceType: "Driver",
            updateType: null,
          },
          aadharNo: null,
          uuid: "0b30550c-6ce7-40b0-8704-4e3f07c5aeee",
          orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
          vehicleRegistrationNumber: "OD-04K-4579 Trailer(H)",
          name: "ABHAY RAJ",
          vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
          associatedUserId: "47408c31-7e64-4d5a-98dd-86a9d5230fd3",
        },
        fleetType: null,
        fleetOwner: null,
        trainInfo: null,
        lbsNumber: null,
        secondaryDriver: null,
        device: null,
        status: null,
      },
      syncUpDueTime: null,
      currentLocation: null,
      alerts: null,
      equipments: null,
      tripType: null,
      poLineItemId: null,
      consignments: null,
      customContacts: null,
      shipmentStages: [
        {
          departureTime: null,
          gateInTime: null,
          actualActivityStartTime: null,
          actualActivityEndTime: null,
          uuid: "bdc0ff2a-aa72-41ca-a352-00d551fd1a0d",
          consignmentDelivered: null,
          resourceDropOff: null,
          resourcePickup: null,
          eta: 1603406090000,
          stageName: null,
          hub: {
            hubId: null,
            boundary: null,
            address: "PATNA ,INDIA",
            accessibility: "private",
            addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
            center: {
              latitude: 25.5940947,
              longitude: 85.1375645,
            },
            suggestedRadius: 100000,
            isOwned: null,
            centerCoordinates: [85.1375645, 25.5940947],
            placeId: "53fc257c-1530-4bda-9c13-71c65b6b9a62",
            geoJsonBoundry: null,
            externalId: "04PANA",
            source: "hubs",
            places: [],
            viewport: {
              southwest: {
                latitude: 24.99730898,
                longitude: 84.40026535199999,
              },
              northeast: {
                latitude: 26.19088042,
                longitude: 85.874863648,
              },
            },
            district: null,
            name: "PATNA",
            state: null,
            category: "Hub",
            subDistrict: null,
          },
          arrivalTime: 1603395722000,
          expectedActivityStartTime: null,
          secondaryStatus: "WaitingForGateIn",
          consignmentPickUps: null,
          tripPoint: {
            outOfTrackSince: null,
            creationTime: 1603708586126,
            purpose: "Pickup",
            plannedArrival: null,
            currentGpsState: null,
            updates: {
              traceID: null,
              resourceId: "bdc0ff2a-aa72-41ca-a352-00d551fd1a0d",
              updatedBy: "SYSTEM",
              sourceOfInformation: null,
              description: null,
              forwardReasons: ["trippoint.status.updated", "trippoint.updated"],
              userId: null,
              uuid: "75f94588-d39d-4a08-a111-7b0eb7d132db",
              revision: 1,
              time: 1603708945023,
              forwardedFrom: null,
              resourceType: "TripPoint",
              updateType: null,
            },
            uuid: "bdc0ff2a-aa72-41ca-a352-00d551fd1a0d",
            sequenceId: null,
            isDisconnected: false,
            isOutOfTrack: false,
            routeDeviationMinimumDistanceConstraint: null,
            eta: 1603406090000,
            routeId: null,
            expectedActivityStartTime: null,
            actualDeparture: null,
            vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
            place: null,
            remainingDistance: null,
            actualActivityStartTime: null,
            forShipmentStages: ["bdc0ff2a-aa72-41ca-a352-00d551fd1a0d"],
            actualActivityEndTime: null,
            actualArrival: 1603395722000,
            purposedDistance: null,
            plannedDeparture: null,
            currentLocation: null,
            isAutoCompleted: false,
            coveredDistance: null,
            hub: {
              hubId: null,
              boundary: null,
              address: "PATNA ,INDIA",
              accessibility: "private",
              addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
              center: {
                latitude: 25.5940947,
                longitude: 85.1375645,
              },
              suggestedRadius: 100000,
              isOwned: null,
              centerCoordinates: [85.1375645, 25.5940947],
              placeId: "53fc257c-1530-4bda-9c13-71c65b6b9a62",
              geoJsonBoundry: null,
              externalId: "04PANA",
              source: "hubs",
              places: [],
              viewport: {
                southwest: {
                  latitude: 24.99730898,
                  longitude: 84.40026535199999,
                },
                northeast: {
                  latitude: 26.19088042,
                  longitude: 85.874863648,
                },
              },
              district: null,
              name: "PATNA",
              state: null,
              category: "Hub",
              subDistrict: null,
            },
            imei: "6a721839-d120-43da-bf94-dbd488e9e633",
            assosiatedShipmentsId: ["0ffcb6ef-ace3-41e1-9ad3-660a2a5d92e2"],
            status: "AT",
          },
          place: null,
          status: "AT",
        },
        {
          departureTime: null,
          gateInTime: null,
          actualActivityStartTime: null,
          actualActivityEndTime: null,
          uuid: "cd0e61b2-39b1-4203-a3a0-bace8d8894fd",
          consignmentDelivered: null,
          resourceDropOff: null,
          resourcePickup: null,
          eta: 1603463768000,
          stageName: null,
          hub: {
            hubId: null,
            boundary: null,
            address: "DURGAPUR ,INDIA",
            accessibility: "private",
            addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
            center: {
              latitude: 23.5204,
              longitude: 87.3119,
            },
            suggestedRadius: 100000,
            isOwned: null,
            centerCoordinates: [87.3119, 23.5204],
            placeId: "53cc8032-858d-47b6-ac0d-3f60dbf25dcf",
            geoJsonBoundry: null,
            externalId: "25DRGP",
            source: "hubs",
            places: [],
            viewport: {
              southwest: {
                latitude: 22.92361428,
                longitude: 86.57460085199999,
              },
              northeast: {
                latitude: 24.11718572,
                longitude: 88.049199148,
              },
            },
            district: null,
            name: "DURGAPUR",
            state: null,
            category: "Hub",
            subDistrict: null,
          },
          arrivalTime: null,
          expectedActivityStartTime: null,
          secondaryStatus: null,
          consignmentPickUps: null,
          tripPoint: {
            outOfTrackSince: null,
            creationTime: null,
            purpose: "Delivery",
            plannedArrival: null,
            currentGpsState: null,
            updates: null,
            uuid: "cd0e61b2-39b1-4203-a3a0-bace8d8894fd",
            sequenceId: null,
            isDisconnected: false,
            isOutOfTrack: false,
            routeDeviationMinimumDistanceConstraint: null,
            eta: 1603463768000,
            routeId: null,
            expectedActivityStartTime: null,
            actualDeparture: null,
            vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
            place: null,
            remainingDistance: null,
            actualActivityStartTime: null,
            forShipmentStages: ["cd0e61b2-39b1-4203-a3a0-bace8d8894fd"],
            actualActivityEndTime: null,
            actualArrival: null,
            purposedDistance: null,
            plannedDeparture: null,
            currentLocation: null,
            isAutoCompleted: false,
            coveredDistance: null,
            hub: {
              hubId: null,
              boundary: null,
              address: "DURGAPUR ,INDIA",
              accessibility: "private",
              addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
              center: {
                latitude: 23.5204,
                longitude: 87.3119,
              },
              suggestedRadius: 100000,
              isOwned: null,
              centerCoordinates: [87.3119, 23.5204],
              placeId: "53cc8032-858d-47b6-ac0d-3f60dbf25dcf",
              geoJsonBoundry: null,
              externalId: "25DRGP",
              source: "hubs",
              places: [],
              viewport: {
                southwest: {
                  latitude: 22.92361428,
                  longitude: 86.57460085199999,
                },
                northeast: {
                  latitude: 24.11718572,
                  longitude: 88.049199148,
                },
              },
              district: null,
              name: "DURGAPUR",
              state: null,
              category: "Hub",
              subDistrict: null,
            },
            imei: "6a721839-d120-43da-bf94-dbd488e9e633",
            assosiatedShipmentsId: ["0ffcb6ef-ace3-41e1-9ad3-660a2a5d92e2"],
            status: "NEXT",
          },
          place: null,
          status: "NEXT",
        },
      ],
      remarks: null,
      shipmentStatus: null,
    },
    accessibleTo: null,
    vehicle: {
      vtsDeviceId: null,
      kmDriven: null,
      attachedDocs: [],
      customFields: [
        {
          indexedValue: ["SupervisorEmail_AMRIK.LAYAL@DARCL.COM"],
          fieldKey: "SupervisorEmail",
          valueType: "string",
          fieldType: "text",
          value: "AMRIK.LAYAL@DARCL.COM",
          definitionId: null,
        },
      ],
      floorType: null,
      source: "FRETRON",
      isTrackingEnabled: false,
      updates: {
        traceID: null,
        resourceId: "6a721839-d120-43da-bf94-dbd488e9e633",
        updatedBy: "SYSTEM",
        sourceOfInformation: null,
        description: null,
        forwardReasons: ["vehicle.remove.from.group"],
        userId: null,
        uuid: "d425f9e2-d0f7-47d6-87e8-b96799af6102",
        revision: null,
        time: 1609934112133,
        forwardedFrom: null,
        resourceType: "Vehicle",
        updateType: null,
      },
      uuid: "6a721839-d120-43da-bf94-dbd488e9e633",
      branch: {
        address:
          "PLOT NO. 2963, Near Samal Petrol Pump Tata Motors Ltd ,Santari Chhak Banarpal,  ",
        updatedBy: "d1b5a45c-9005-4061-a5f4-411dec2bef88",
        customFields: [
          {
            indexedValue: ["BranchCodes_FMMRF"],
            fieldKey: "BranchCodes",
            valueType: "arrayOfString",
            fieldType: "select",
            value: '["FMMRF"]',
            definitionId: null,
          },
        ],
        regionName: "ORISSA REGION",
        externalId: "1929",
        branchName: "FLEET-MERAMUNDALI-F",
        type: ["Operation"],
        updates: null,
        orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
        geoLocation: [85.3355893, 20.7787579],
        regionId: "8e300247-88bd-4a2c-a9e2-f3d6cfacb652",
        name: "FLEET-MERAMUNDALI-F",
        zoneId: "f05da103-eab5-4419-969b-e26fdc19075a",
        _id: "24f792d2-7637-4b8e-831f-82610f75bc51",
        zoneName: "BU-South",
        contacts: [
          {
            emails: ["mohan.sharma@cjdarcl.com"],
            address: null,
            mobileNumbers: ["9611392319"],
            mobileNumber: null,
            name: "FLEET-MERAMUNDALI-F",
            type: null,
          },
        ],
        officeType: null,
        materialServices: null,
      },
      orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
      vehicleLoadType: null,
      associatedWith: null,
      isDeleted: null,
      customerId: "d1b5a45c-9005-4061-a5f4-411dec2bef88",
      vehicleModel: "4018TC",
      mileageEmpty: null,
      mileageLoaded: null,
      vehicleType: "fleet",
      groups: [],
      externalId: "000000000010115195",
      updateTime: 1609934112133,
      sharedWith: ["FRETRON_GOD_FO"],
      vehicleMake: "Tata Motors",
      vehicleRegistrationNumber: "OD-04K-4579 Trailer(H)",
      chassisNumber: "MAT447230H3J23499",
      driverId: "9f628ead-c6f6-4406-8756-8c31b03a1c88",
      createTime: 1601469372787,
      loadCapacity: 32,
      truckLength: null,
      category: null,
      groupsExtended: [],
    },
    driver: {
      pincode: null,
      dlExpiryTime: null,
      attachedDocs: [],
      address: null,
      mobileNumbers: null,
      dlNumber: null,
      mobileNumber: null,
      customFields: null,
      externalId: "00112516",
      updates: {
        traceID: null,
        resourceId: "9f628ead-c6f6-4406-8756-8c31b03a1c88",
        updatedBy: "USER",
        sourceOfInformation: null,
        description:
          "changed mobile number from 9996630020 to  and changed driving license expire date from 18/01/2021  to 18/01/2021 ",
        forwardReasons: [
          "driver.update.event",
          "driver.mobile.number.updated",
          "driver.license.expiry.date.updated",
        ],
        userId: "47408c31-7e64-4d5a-98dd-86a9d5230fd3",
        uuid: "5c79e3c0-e3d2-4ae3-b3a5-a8c292057d38",
        revision: null,
        time: 1610953202588,
        forwardedFrom: null,
        resourceType: "Driver",
        updateType: null,
      },
      aadharNo: null,
      uuid: "9f628ead-c6f6-4406-8756-8c31b03a1c88",
      orgId: "c24f7c91-30ba-4533-b86d-9eca644e6605",
      vehicleRegistrationNumber: "OD-04K-4579 Trailer(H)",
      name: "ANIL YADAV",
      vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
      associatedUserId: null,
    },
    lastForwardTime: null,
    activeIssues: [
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "4fac92af-cabe-48b7-a917-19be92d2a157",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "447d1999-3f5e-4aad-a1f5-17519699fb17",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "668c286c-86aa-44f6-9f17-d3c4052f91d8",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Driver Expense Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "cf873d39-98ac-47f5-8b9a-acfa1052307a",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "a2315771-f5fe-481d-ba04-e3eb92b10b57",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "3e0ad838-9dcc-496a-b122-d011c5ccab69",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Salary Issue By driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "920a0529-b3b2-4c67-b50b-40215e9aaff1",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "9403cc08-294a-43f6-a956-1f717e966bcd",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "a78d2d10-2e12-40d4-871c-1fa065d361fa",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Salary Issue By driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "b7e4b6f4-2ba4-42ac-af3d-3fc66e6dc178",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "8495f670-b258-43e0-a549-b7adfb4f83cd",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "5593b363-135b-4cf1-9afd-06aa3a4c520b",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "7abbe376-fd03-4091-ac2c-854cf8f5d7d8",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "fff6c323-ac23-4a2e-9152-34e8d141c016",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "68c72bfc-183b-47b3-90e9-2528fd3042f3",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "3ec0549a-a139-4fe5-b837-72f8b9e503e5",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "64e9d397-4220-4de6-b459-b4f8470a6f5d",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "78512b8e-c204-49da-a166-b27fa5f4e067",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "4f3c1c6f-1397-4bbe-b061-a89967b6b517",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "d2402a7d-7ccc-4642-94eb-a59e5bc25227",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Load Request",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "c2f050b7-8e48-45a5-9a4e-730bb58d2115",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "05f8d716-8f37-46aa-902a-95d959e7d91c",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "7288eba3-109b-4fb5-8013-341b8d9f627d",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "4a1ab41f-8e78-4548-94a7-450a281cb0fc",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Salary Issue By driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
      {
        resourceId: null,
        attachments: null,
        customeFields: null,
        customFields: null,
        resolutionDate: null,
        source: null,
        updates: null,
        issueNo: null,
        uuid: "ac892c4c-fceb-4c5f-a6d1-e29ee9dba70f",
        branch: null,
        orgId: null,
        createdAt: null,
        issueTypeId: null,
        escalationPerson: null,
        userWatchers: null,
        descriptionHTML: null,
        filterTags: null,
        escalationDueDate: null,
        updatedAt: null,
        holdOnTime: null,
        dueDateExtensions: null,
        issueSummery: null,
        creator: null,
        resolutionDuration: null,
        updatedBy: null,
        comments: null,
        onHoldDueTo: null,
        showIn: null,
        reporter: null,
        priority: null,
        escalationLevel: null,
        parentId: null,
        tags: null,
        issueType: "Vehicle Maintenance request by Driver",
        dueAt: null,
        estimatedResolutionDate: null,
        bpartnerFollowers: null,
        resourceIdentifier: null,
        escalationName: null,
        secondaryStatus: null,
        bpartnerWatchers: null,
        assignee: null,
        category: null,
        subIssues: null,
        userFollowers: null,
        issueDescription: null,
        resourceType: null,
        status: null,
      },
    ],
    secondaryStatus: null,
    activeIssuesCount: 25,
    vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
    tripPoint: {
      outOfTrackSince: null,
      creationTime: 1603708586126,
      purpose: "Pickup",
      plannedArrival: null,
      currentGpsState: null,
      updates: {
        traceID: null,
        resourceId: "bdc0ff2a-aa72-41ca-a352-00d551fd1a0d",
        updatedBy: "SYSTEM",
        sourceOfInformation: null,
        description: null,
        forwardReasons: ["trippoint.status.updated", "trippoint.updated"],
        userId: null,
        uuid: "75f94588-d39d-4a08-a111-7b0eb7d132db",
        revision: 1,
        time: 1603708945023,
        forwardedFrom: null,
        resourceType: "TripPoint",
        updateType: null,
      },
      uuid: "bdc0ff2a-aa72-41ca-a352-00d551fd1a0d",
      sequenceId: null,
      isDisconnected: false,
      isOutOfTrack: false,
      routeDeviationMinimumDistanceConstraint: null,
      eta: 1603406090000,
      routeId: null,
      expectedActivityStartTime: null,
      actualDeparture: null,
      vehicleId: "6a721839-d120-43da-bf94-dbd488e9e633",
      place: null,
      remainingDistance: null,
      actualActivityStartTime: null,
      forShipmentStages: ["bdc0ff2a-aa72-41ca-a352-00d551fd1a0d"],
      actualActivityEndTime: null,
      actualArrival: 1603395722000,
      purposedDistance: null,
      plannedDeparture: null,
      currentLocation: null,
      isAutoCompleted: false,
      coveredDistance: null,
      hub: {
        hubId: null,
        boundary: null,
        address: "PATNA ,INDIA",
        accessibility: "private",
        addedBy: "c24f7c91-30ba-4533-b86d-9eca644e6605",
        center: {
          latitude: 25.5940947,
          longitude: 85.1375645,
        },
        suggestedRadius: 100000,
        isOwned: null,
        centerCoordinates: [85.1375645, 25.5940947],
        placeId: "53fc257c-1530-4bda-9c13-71c65b6b9a62",
        geoJsonBoundry: null,
        externalId: "04PANA",
        source: "hubs",
        places: [],
        viewport: {
          southwest: {
            latitude: 24.99730898,
            longitude: 84.40026535199999,
          },
          northeast: {
            latitude: 26.19088042,
            longitude: 85.874863648,
          },
        },
        district: null,
        name: "PATNA",
        state: null,
        category: "Hub",
        subDistrict: null,
      },
      imei: "6a721839-d120-43da-bf94-dbd488e9e633",
      assosiatedShipmentsId: ["0ffcb6ef-ace3-41e1-9ad3-660a2a5d92e2"],
      status: "AT",
    },
    activeAlerts: null,
    remarks: null,
    gpsState: null,
    status: "At pickup",
    updatedAt: null,
  },
};
var test = execute();
function execute() {
  let fleetInfo = {};

  fleetInfo["vehicle"] = suggetion.vlr.vehicle;
  fleetInfo["driver"] = suggetion.vlr.driver;
  fleetInfo["trackingMode"] = "MANUAL";
  fleetInfo["fleetType"] = "Owned";
  fleetInfo["device"] = null
  if (suggetion.vlr.vehicle.vtsDeviceId) {
    fleetInfo["device"] = {
      imei: suggetion.vlr.vehicle.vtsDeviceId,
    };
    fleetInfo["trackingMode"] = "TRACKNET";
  }
  console.log(fleetInfo);
}
