var vehicleAssignmentFields =[
  {
    isApplicable: true,
    isRequired: true,
    fieldType: "",
    fieldName: "VehicleNo",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: true,
  },
  {
    isApplicable: true,
    isRequired: true,
    fieldType: "",
    fieldName: "VehicleType",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: true,
  },
  {
    isApplicable: true,
    isRequired: true,
    fieldType: "",
    fieldName: "LoadCapacity",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: true,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "RCInfo",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },

  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "InsuranceInfo",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "PollutionInfo",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "DriverName",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "DateOfBirth",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "CurrentAge",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "MobileNumber",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "MobileModel",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "SmartPhone",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "DrivingLicense",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "LicenseCopy",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "DrivingLicenseExpiry",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "FreightChargeRate",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },
  {
    isApplicable: true,
    isRequired: false,
    fieldType: "",
    fieldName: "FreightChargeType",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: false,
  },

  {
    isApplicable: true,
    isRequired: true,
    fieldType: "",
    fieldName: "Vendor",
    isMultipleChoice: false,
    defaultValue: "",
    isSystemDefined: true,
  },
];
  console.log( vehicleAssignmentFields.map((value)=>value.fieldName))